### ISSUE TITLE
Fails to build under node 0.12.x

### ISSUE THREAD

**Issue by natevw** [samshull/node-proxy#39]
I know I can now start scripts with `node --harmony-proxies` to get V8 built-in support for `Proxy` but for scripts that still depend on this library (and situations where it's a pain to start node with custom flags), I'm wondering if this is a simple fix to get it working again?

Complete log here:
https://gist.github.com/natevw/c45b5abdc79f34c84729

**Comment by samshull** [comment]
fixed by https://github.com/samshull/node-proxy/commit/7aa4c269079d95b59ff2e39b76e46abc434635e4

**Comment by natevw** [comment]
Awesome, thanks for the quick turnaround! (I'm using this in https://github.com/natevw/fermata — and the version where it's an *optional* dependency is still under development, so this will be appreciated by users of the stable version where it's still required.)
